# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.0

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:
.PHONY : .NOTPARALLEL

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/580F625C089B22E0/Universidad/4/CuatrimestreII/Metaheurísticas/Práctica Final/prueba"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/580F625C089B22E0/Universidad/4/CuatrimestreII/Metaheurísticas/Práctica Final/prueba"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/580F625C089B22E0/Universidad/4/CuatrimestreII/Metaheurísticas/Práctica Final/prueba/CMakeFiles" "/mnt/580F625C089B22E0/Universidad/4/CuatrimestreII/Metaheurísticas/Práctica Final/prueba/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/580F625C089B22E0/Universidad/4/CuatrimestreII/Metaheurísticas/Práctica Final/prueba/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named example_ls

# Build rule for target.
example_ls: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 example_ls
.PHONY : example_ls

# fast build rule for target.
example_ls/fast:
	$(MAKE) -f CMakeFiles/example_ls.dir/build.make CMakeFiles/example_ls.dir/build
.PHONY : example_ls/fast

#=============================================================================
# Target rules for targets named localsearch

# Build rule for target.
localsearch: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 localsearch
.PHONY : localsearch

# fast build rule for target.
localsearch/fast:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/build
.PHONY : localsearch/fast

# target to build an object file
aux.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/aux.o
.PHONY : aux.o

# target to preprocess a source file
aux.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/aux.i
.PHONY : aux.i

# target to generate assembly for a file
aux.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/aux.s
.PHONY : aux.s

# target to build an object file
cec2014_func.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/cec2014_func.o
.PHONY : cec2014_func.o

# target to preprocess a source file
cec2014_func.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/cec2014_func.i
.PHONY : cec2014_func.i

# target to generate assembly for a file
cec2014_func.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/cec2014_func.s
.PHONY : cec2014_func.s

# target to build an object file
cmaeshan.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/cmaeshan.o
.PHONY : cmaeshan.o

# target to preprocess a source file
cmaeshan.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/cmaeshan.i
.PHONY : cmaeshan.i

# target to generate assembly for a file
cmaeshan.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/cmaeshan.s
.PHONY : cmaeshan.s

# target to build an object file
domain.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/domain.o
.PHONY : domain.o

# target to preprocess a source file
domain.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/domain.i
.PHONY : domain.i

# target to generate assembly for a file
domain.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/domain.s
.PHONY : domain.s

# target to build an object file
example.o:
	$(MAKE) -f CMakeFiles/example_ls.dir/build.make CMakeFiles/example_ls.dir/example.o
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/example.o
.PHONY : example.o

# target to preprocess a source file
example.i:
	$(MAKE) -f CMakeFiles/example_ls.dir/build.make CMakeFiles/example_ls.dir/example.i
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/example.i
.PHONY : example.i

# target to generate assembly for a file
example.s:
	$(MAKE) -f CMakeFiles/example_ls.dir/build.make CMakeFiles/example_ls.dir/example.s
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/example.s
.PHONY : example.s

# target to build an object file
metaheuristic.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/metaheuristic.o
.PHONY : metaheuristic.o

# target to preprocess a source file
metaheuristic.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/metaheuristic.i
.PHONY : metaheuristic.i

# target to generate assembly for a file
metaheuristic.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/metaheuristic.s
.PHONY : metaheuristic.s

# target to build an object file
origcmaes.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/origcmaes.o
.PHONY : origcmaes.o

# target to preprocess a source file
origcmaes.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/origcmaes.i
.PHONY : origcmaes.i

# target to generate assembly for a file
origcmaes.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/origcmaes.s
.PHONY : origcmaes.s

# target to build an object file
problem.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/problem.o
.PHONY : problem.o

# target to preprocess a source file
problem.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/problem.i
.PHONY : problem.i

# target to generate assembly for a file
problem.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/problem.s
.PHONY : problem.s

# target to build an object file
problemcec2014.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/problemcec2014.o
.PHONY : problemcec2014.o

# target to preprocess a source file
problemcec2014.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/problemcec2014.i
.PHONY : problemcec2014.i

# target to generate assembly for a file
problemcec2014.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/problemcec2014.s
.PHONY : problemcec2014.s

# target to build an object file
random.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/random.o
.PHONY : random.o

# target to preprocess a source file
random.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/random.i
.PHONY : random.i

# target to generate assembly for a file
random.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/random.s
.PHONY : random.s

# target to build an object file
simplex.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/simplex.o
.PHONY : simplex.o

# target to preprocess a source file
simplex.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/simplex.i
.PHONY : simplex.i

# target to generate assembly for a file
simplex.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/simplex.s
.PHONY : simplex.s

# target to build an object file
solis.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/solis.o
.PHONY : solis.o

# target to preprocess a source file
solis.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/solis.i
.PHONY : solis.i

# target to generate assembly for a file
solis.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/solis.s
.PHONY : solis.s

# target to build an object file
solution.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/solution.o
.PHONY : solution.o

# target to preprocess a source file
solution.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/solution.i
.PHONY : solution.i

# target to generate assembly for a file
solution.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/solution.s
.PHONY : solution.s

# target to build an object file
srandom.o:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/srandom.o
.PHONY : srandom.o

# target to preprocess a source file
srandom.i:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/srandom.i
.PHONY : srandom.i

# target to generate assembly for a file
srandom.s:
	$(MAKE) -f CMakeFiles/localsearch.dir/build.make CMakeFiles/localsearch.dir/srandom.s
.PHONY : srandom.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... example_ls"
	@echo "... localsearch"
	@echo "... rebuild_cache"
	@echo "... aux.o"
	@echo "... aux.i"
	@echo "... aux.s"
	@echo "... cec2014_func.o"
	@echo "... cec2014_func.i"
	@echo "... cec2014_func.s"
	@echo "... cmaeshan.o"
	@echo "... cmaeshan.i"
	@echo "... cmaeshan.s"
	@echo "... domain.o"
	@echo "... domain.i"
	@echo "... domain.s"
	@echo "... example.o"
	@echo "... example.i"
	@echo "... example.s"
	@echo "... metaheuristic.o"
	@echo "... metaheuristic.i"
	@echo "... metaheuristic.s"
	@echo "... origcmaes.o"
	@echo "... origcmaes.i"
	@echo "... origcmaes.s"
	@echo "... problem.o"
	@echo "... problem.i"
	@echo "... problem.s"
	@echo "... problemcec2014.o"
	@echo "... problemcec2014.i"
	@echo "... problemcec2014.s"
	@echo "... random.o"
	@echo "... random.i"
	@echo "... random.s"
	@echo "... simplex.o"
	@echo "... simplex.i"
	@echo "... simplex.s"
	@echo "... solis.o"
	@echo "... solis.i"
	@echo "... solis.s"
	@echo "... solution.o"
	@echo "... solution.i"
	@echo "... solution.s"
	@echo "... srandom.o"
	@echo "... srandom.i"
	@echo "... srandom.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

